version: '3.8'

services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=junction.proxy.rlwy.net
      - DB_PORT=24066
      - DB_USERNAME=root
      - DB_PASSWORD=pCLVMAewIJaSEAjdxXMQSpZBHWsqwqpA
      - DB_DATABASE_NAME=hairhub
    networks:
      - app-network

networks:
  app-network:
    driver: bridge